package luau

type Opcode byte

const (
	OpNOP Opcode = iota
	OpBREAK
	OpLOADNIL
	OpLOADB
	OpLOADN
	OpLOADK
	OpMOVE
	OpGETGLOBAL
	OpSETGLOBAL
	OpGETUPVAL
	OpSETUPVAL
	OpCLOSEUPVALS
	OpGETIMPORT
	OpGETTABLE
	OpSETTABLE
	OpGETTABLEKS
	OpSETTABLEKS
	OpGETTABLEN
	OpSETTABLEN
	OpNEWCLOSURE
	OpNAMECALL
	OpCALL
	OpRETURN
	OpJUMP
	OpJUMPBACK
	OpJUMPIF
	OpJUMPIFNOT
	OpJUMPIFEQ
	OpJUMPIFLE
	OpJUMPIFLT
	OpJUMPIFNOTEQ
	OpJUMPIFNOTLE
	OpJUMPIFNOTLT
	OpADD
	OpSUB
	OpMUL
	OpDIV
	OpMOD
	OpPOW
	OpADDK
	OpSUBK
	OpMULK
	OpDIVK
	OpMODK
	OpPOWK
	OpAND
	OpOR
	OpANDK
	OpORK
	OpCONCAT
	OpNOT
	OpMINUS
	OpLENGTH
	OpNEWTABLE
	OpDUPTABLE
	OpSETLIST
	OpFORNPREP
	OpFORNLOOP
	OpFORGLOOP
	OpFORGPREPINEXT
	OpFASTCALL3
	OpFORGPREPNEXT
	OpNATIVECALL
	OpGETVARARGS
	OpDUPCLOSURE
	OpPREPVARARGS
	OpLOADKX
	OpJUMPX
	OpFASTCALL
	OpCOVERAGE
	OpCAPTURE
	OpSUBRK
	OpDIVRK
	OpFASTCALL1
	OpFASTCALL2
	OpFASTCALL2K
	OpFORGPREP
	OpJUMPXEQKNIL
	OpJUMPXEQKB
	OpJUMPXEQKN
	OpJUMPXEQKS
	OpIDIV
	OpIDIVK
	OpGETUDATAKS
	OpSETUDATAKS
	OpNAMECALLUDATA
	OpNEWCLASSMEMBER
	OpCALLFB
	OpCMPPROTO
	OpFASTPCALL
	OpCount
)

var opcodeNames = [OpCount]string{
	OpNOP: "NOP", OpBREAK: "BREAK", OpLOADNIL: "LOADNIL", OpLOADB: "LOADB",
	OpLOADN: "LOADN", OpLOADK: "LOADK", OpMOVE: "MOVE",
	OpGETGLOBAL: "GETGLOBAL", OpSETGLOBAL: "SETGLOBAL",
	OpGETUPVAL: "GETUPVAL", OpSETUPVAL: "SETUPVAL",
	OpCLOSEUPVALS: "CLOSEUPVALS", OpGETIMPORT: "GETIMPORT",
	OpGETTABLE: "GETTABLE", OpSETTABLE: "SETTABLE",
	OpGETTABLEKS: "GETTABLEKS", OpSETTABLEKS: "SETTABLEKS",
	OpGETTABLEN: "GETTABLEN", OpSETTABLEN: "SETTABLEN",
	OpNEWCLOSURE: "NEWCLOSURE", OpNAMECALL: "NAMECALL",
	OpCALL: "CALL", OpRETURN: "RETURN",
	OpJUMP: "JUMP", OpJUMPBACK: "JUMPBACK",
	OpJUMPIF: "JUMPIF", OpJUMPIFNOT: "JUMPIFNOT",
	OpJUMPIFEQ: "JUMPIFEQ", OpJUMPIFLE: "JUMPIFLE", OpJUMPIFLT: "JUMPIFLT",
	OpJUMPIFNOTEQ: "JUMPIFNOTEQ", OpJUMPIFNOTLE: "JUMPIFNOTLE", OpJUMPIFNOTLT: "JUMPIFNOTLT",
	OpADD: "ADD", OpSUB: "SUB", OpMUL: "MUL", OpDIV: "DIV", OpMOD: "MOD", OpPOW: "POW",
	OpADDK: "ADDK", OpSUBK: "SUBK", OpMULK: "MULK", OpDIVK: "DIVK", OpMODK: "MODK", OpPOWK: "POWK",
	OpAND: "AND", OpOR: "OR", OpANDK: "ANDK", OpORK: "ORK",
	OpCONCAT: "CONCAT", OpNOT: "NOT", OpMINUS: "MINUS", OpLENGTH: "LENGTH",
	OpNEWTABLE: "NEWTABLE", OpDUPTABLE: "DUPTABLE", OpSETLIST: "SETLIST",
	OpFORNPREP: "FORNPREP", OpFORNLOOP: "FORNLOOP", OpFORGLOOP: "FORGLOOP",
	OpFORGPREPINEXT: "FORGPREP_INEXT", OpFASTCALL3: "FASTCALL3", OpFORGPREPNEXT: "FORGPREP_NEXT",
	OpNATIVECALL: "NATIVECALL", OpGETVARARGS: "GETVARARGS", OpDUPCLOSURE: "DUPCLOSURE",
	OpPREPVARARGS: "PREPVARARGS", OpLOADKX: "LOADKX", OpJUMPX: "JUMPX",
	OpFASTCALL: "FASTCALL", OpCOVERAGE: "COVERAGE", OpCAPTURE: "CAPTURE",
	OpSUBRK: "SUBRK", OpDIVRK: "DIVRK",
	OpFASTCALL1: "FASTCALL1", OpFASTCALL2: "FASTCALL2", OpFASTCALL2K: "FASTCALL2K",
	OpFORGPREP:    "FORGPREP",
	OpJUMPXEQKNIL: "JUMPXEQKNIL", OpJUMPXEQKB: "JUMPXEQKB",
	OpJUMPXEQKN: "JUMPXEQKN", OpJUMPXEQKS: "JUMPXEQKS",
	OpIDIV: "IDIV", OpIDIVK: "IDIVK",
	OpGETUDATAKS: "GETUDATAKS", OpSETUDATAKS: "SETUDATAKS",
	OpNAMECALLUDATA: "NAMECALLUDATA", OpNEWCLASSMEMBER: "NEWCLASSMEMBER",
	OpCALLFB: "CALLFB", OpCMPPROTO: "CMPPROTO", OpFASTPCALL: "FASTPCALL",
}

func (o Opcode) String() string {
	if o < OpCount {
		return opcodeNames[o]
	}
	return "UNKNOWN"
}

func OpcodeFromByte(b byte) (Opcode, bool) {
	if Opcode(b) < OpCount {
		return Opcode(b), true
	}
	return OpNOP, false
}

func HasAux(o Opcode) bool {
	switch o {
	case OpGETGLOBAL, OpSETGLOBAL, OpGETIMPORT,
		OpGETTABLEKS, OpSETTABLEKS, OpNAMECALL,
		OpJUMPIFEQ, OpJUMPIFLE, OpJUMPIFLT,
		OpJUMPIFNOTEQ, OpJUMPIFNOTLE, OpJUMPIFNOTLT,
		OpNEWTABLE, OpSETLIST, OpFORGLOOP, OpLOADKX,
		OpFASTCALL2, OpFASTCALL2K, OpFASTCALL3,
		OpJUMPXEQKNIL, OpJUMPXEQKB, OpJUMPXEQKN, OpJUMPXEQKS,
		OpGETUDATAKS, OpSETUDATAKS, OpNAMECALLUDATA,
		OpNEWCLASSMEMBER, OpCALLFB, OpCMPPROTO:
		return true
	}
	return false
}
