#!/usr/bin/env python3
"""Generate deterministic de-inline workloads for the existing benchmark tools.

The fixtures exercise small/wide lexical scopes, distinct fixed method names,
successful reconstruction and irrelevant statements. This is a synthetic stress
suite, not a substitute for the project's real-world corpus. Sources, compiler
hash and input hashes are saved so timing results remain reproducible.
Optional replicas amplify short timing samples without changing helper shapes;
an observable replica marker keeps whole-file deduplication from collapsing them.

Example:
  python3 scripts/deinline_workloads.py --compiler /path/to/luau-compile --output out/deinline-workloads
  python3 scripts/benchmark_v2.py --lifter base=/path/to/base --lifter next=/path/to/next \
      --corpus out/deinline-workloads/input --key 1 --threads 1 --rounds 9 \
      --keep out/deinline-timings --report out/deinline-timings.json
"""
import argparse
import base64
import hashlib
import json
from pathlib import Path
import subprocess


WORKLOADS = (
    ("small_scope", 4, 256, True),
    ("wide_scope_hits", 64, 1024, True),
    ("wide_scope_misses", 64, 1024, False),
    ("very_wide_scope_hits", 128, 1024, True),
    ("very_wide_scope_misses", 128, 1024, False),
)


def source(helpers, sites, hits):
    lines = ["-- Generated by scripts/deinline_workloads.py; deterministic synthetic input.",
             "local function make()"]
    for index in range(helpers):
        lines.extend((f"    local function apply{index}(part)",
                      f'        part:Stage{index}("layer")',
                      f'        part:Finish{index}("done")',
                      "    end"))
    lines.append("    local function run(part)")
    for index in range(sites):
        if hits:
            lines.append(f"        apply{index % helpers}(part)")
        else:
            lines.append(f'        part:Unrelated{index % 7}("untouched")')
    lines.extend(("    end", "    return run, {" + ", ".join(f"apply{i}" for i in range(helpers)) + "}",
                  "end", "local total = 0", "local part = setmetatable({}, {",
                  "    __index = function(_, name)",
                  "        return function(_, value) total += #name + #value end",
                  "    end", "})", "local run, helpers = make()", "run(part)",
                  "print(total, #helpers)", ""))
    return "\n".join(lines)


def digest(data):
    return hashlib.sha256(data).hexdigest()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--compiler", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--replicas", type=int, default=1,
                        help="1..64 distinct copies per synthetic scenario (default: 1)")
    args = parser.parse_args()
    if not 1 <= args.replicas <= 64:
        parser.error("--replicas must be between 1 and 64")
    compiler = args.compiler.resolve(strict=True)
    sources = args.output / "source"
    inputs = args.output / "input"
    if any(path.exists() and any(path.iterdir()) for path in (sources, inputs)):
        parser.error("source/input directories must be empty; use a new output directory")
    sources.mkdir(parents=True, exist_ok=True)
    inputs.mkdir(parents=True, exist_ok=True)
    records = []
    for name, helpers, sites, hits in WORKLOADS:
        for replica in range(args.replicas):
            case = name if args.replicas == 1 else f"{name}_r{replica:02d}"
            code = source(helpers, sites, hits)
            if args.replicas > 1:
                code += f'print("replica-{replica}")\n'
            code = code.encode("utf-8")
            path = sources / f"{case}.luau"
            path.write_bytes(code)
            command = [str(compiler), "--binary", "-O2", "-g1", "--fflags=false", str(path)]
            compiled = subprocess.run(command, capture_output=True, timeout=60, check=True)
            if not compiled.stdout or compiled.stdout[0] != 9:
                raise ValueError(f"{case}: expected Luau bytecode version 9")
            saved = base64.b64encode(compiled.stdout) + b"\n"
            (inputs / f"{case}.lua").write_bytes(saved)
            records.append(dict(name=case, scenario=name, replica=replica,
                                helpers=helpers, sites=sites, hits=hits,
                                source_sha256=digest(code), input_sha256=digest(saved),
                                bytecode_sha256=digest(compiled.stdout),
                                bytecode_bytes=len(compiled.stdout)))
    manifest = dict(schema_version=1, synthetic=True, decode_key=1, replicas=args.replicas,
                    generator_sha256=digest(Path(__file__).read_bytes()),
                    compiler_sha256=digest(compiler.read_bytes()),
                    compiler_arguments=["--binary", "-O2", "-g1", "--fflags=false"],
                    workloads=records)
    (args.output / "workloads.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"Generated {len(records)} workloads in {args.output}")


if __name__ == "__main__":
    main()
